version: '3.9'

services:
  mysql:
    image: mysql:5.7.25
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql:cached

volumes:
    mysql-data:
        external: false
